service: aws-serverless-experiments

functions:
  main:
    handler: dist/main.handler
    description: API for experimenting purpose
    provisionedConcurrency: 2
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

custom:
  serverless-offline:
    noPrependStageInUrl: true
    httpPort: 9090

provider:
  profile: chandan-vishwakarma-experiments
  name: aws
  region: ap-south-1
  stage: dev
  runtime: nodejs18.x
  memorySize: 256
  timeout: 10
  lambdaHashingVersion: 20201221
  logRetentionInDays: 1

package:
  individually: true
  exclude:
    - './**'
  include:
    - 'dist/**'

plugins:
  - serverless-offline
