service: aws-serverless-experiments

functions:
  main:
    handler: src/lambda.handler
    description: API for experimenting purpose
    lambdaInsights: true
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
  websocket-handler:
    handler: src/websocket/websocket-handler.handler
    description: Websocket connection management handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
      - websocket:
          route: ping
      - websocket:
          route: message

custom:
  serverless-offline:
    noPrependStageInUrl: true
    httpPort: 9090

  webpack:
    webpackConfig: 'webpack.config.js'
    concurrency: 2

provider:
  profile: chandan-vishwakarma-experiments
  name: aws
  region: ap-south-1
  stage: dev
  runtime: nodejs18.x
  memorySize: 256
  timeout: 10
  lambdaHashingVersion: 20201221
  logRetentionInDays: 1
  websocketsApiName: ${self:service}
  websocketsDescription: Sample Websockets Project

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-plugin-lambda-insights
