service: aws-serverless-experiments

custom:
  serverless-offline:
    noPrependStageInUrl: true
    httpPort: 9090

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

package:
  individually: true
  exclude:
    - './**'
  include:
    - 'dist/**'
