service: aws-serverless-experiments

useDotenv: true

functions:
  main:
    handler: src/lambda.handler
    description: API for experimenting purpose
    lambdaInsights: true
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
  websocket-handler:
    handler: src/websocket/websocket-handler.handler
    description: Websocket connection management handler
    lambdaInsights: true
    environment:
      AWS_WEBSOCKET_API_ID: ${env:AWS_WEBSOCKET_API_ID}
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: message

custom:
  serverless-offline:
    noPrependStageInUrl: true
    httpPort: 9090

  webpack:
    webpackConfig: 'webpack.config.js'
    concurrency: 2

provider:
  profile: chandan-vishwakarma-experiments
  name: aws
  region: ap-south-1
  stage: dev
  runtime: nodejs18.x
  memorySize: 256
  timeout: 10
  lambdaHashingVersion: 20201221
  logRetentionInDays: 1
  websocketsApiName: ${self:service}
  websocketsApiRouteSelectionExpression: $request.body.action
  websocketsDescription: Sample Websockets Project
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:BatchGet*
            - dynamodb:BatchWrite*
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:service}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:service}/index/*
  environment:
    REGION: ${env:REGION}
    TABLE_NAME: ${env:TABLE_NAME}

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-plugin-lambda-insights
